# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-13 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocplus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocplus.Language')),
            ],
            options={
                'ordering': ['text'],
                'db_table': 'Word',
            },
        ),
    ]
