# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-13 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocplus', '0002_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocplus.Word', unique=True)),
            ],
            options={
                'ordering': ['position'],
                'db_table': 'WordRank',
            },
        ),
    ]
