# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-13 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocplus', '0003_wordrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordrank',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vocplus.Word'),
        ),
    ]
