# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-14 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocplus', '0005_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocplus.Lesson')),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vocplus.Word')),
            ],
            options={
                'db_table': 'LessonWord',
            },
        ),
    ]
