# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-14 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocplus', '0006_lessonword'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('media_type', models.CharField(choices=[('V', 'Video'), ('I', 'Image'), ('T', 'Text'), ('P', 'Podcast')], max_length=1)),
                ('link', models.URLField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocplus.Lesson')),
            ],
            options={
                'db_table': 'LessonMedia',
            },
        ),
    ]
