# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocplus', '0009_usercomplement_userlearninglanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='sequence',
            field=models.IntegerField(unique=True),
        ),
    ]
