# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocplus', '0010_auto_20180123_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlearninglanguage',
            name='last_access',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wordrank',
            name='position',
            field=models.IntegerField(db_index=True),
        ),
    ]
