# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vocplus', '0013_auto_20180629_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlearninglanguage',
            name='last_access',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
