# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170728_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularexpression',
            name='name',
            field=models.CharField(default='Generic', max_length=50),
        ),
    ]
