# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_regularexpression_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularexpression',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
