# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170728_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleword',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
