# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170730_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word']},
        ),
    ]
