# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-05 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170807_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path_to_image',
            field=models.CharField(max_length=100, null=True, verbose_name='Caminho para a imagem.'),
        ),
    ]
