# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-12 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_category_path_to_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumedArticleWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ArticleLesson')),
                ('word_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Word')),
            ],
        ),
    ]
